### ISSUE TITLE
No /heads add in available commands

### ISSUE THREAD

**Issue by xleb-normal** [EternalCodeTeam/LobbyHeads#17]
When I add this plugin to the server and enter /head add, it writes to me that there is no such command

- Minecraft Version: 1.19.4
- LobbyHeads Version: 1.0.1
- Server Platform: Paper
- Server Version: 1.19.4
- Java Version: 17

**Comment by vLuckyyy** [comment]
1. Is the plugin really launched? (see logs)
2. To Set the head, you need to take the player's head from gamemode creative, place it anywhere, and then type the command /heads add while looking at the head.
3. Are you sure you have permission to execute this command?
4. Do you want to attach screen?

**Comment by xleb-normal** [comment]
> 1. Is the plugin really launched? (see logs)
> 2. To Set the head, you need to take the player's head from gamemode creative, place it anywhere, and then type the command /heads add while looking at the head.
> 3. Are you sure you have permission to execute this command?
> 4. Do you want to attach screen?

1. Yes
2. Yes
3. Yes

**Comment by vLuckyyy** [comment]
You can attach screen of this problem?

**Comment by xleb-normal** [comment]
> You can attach screen of this problem?

I tried re-downloading the plugin to the server and it worked, apparently something went wrong last time, sorry for the false report

**Comment by vLuckyyy** [comment]
No problem, thanks for using lobbyheads!
